### ISSUE TITLE
Clippy failing with no errors:`[error]Invalid request.`

### ISSUE THREAD

**Issue by matchai** [actions-rs/clippy-check#1]
Hey @svartalf!

I'm looking forward to using `clippy-check`. Unfortunately I'm running into a bug when using it in CI with clippy stable with an unusual message:
```
Clippy results: 0 ICE, 0 errors, 462 warnings, 0 notes, 0 help
##[error]Invalid request.

No more than 50 items are allowed; 51 were supplied.
##[error]Node run failed with exit code 1
```

Here's a link to the failing build:
https://github.com/starship/starship/pull/455/checks?check_run_id=241891945

**Comment by svartalf** [comment]
Hey, @matchai, thank you for a bug report!

Can I ask you to change the Action version temporary from this one:

```yaml
- uses: actions-rs/clippy-check@v1
```

to the
```yaml
uses: actions-rs/clippy-check@bucket-size
```
?

**Comment by matchai** [comment]
It appears to cause a similar failure:
https://github.com/starship/starship/pull/455/checks?check_run_id=242588422

**Comment by svartalf** [comment]
Ah, yes, my bad, could you just restart this workflow once again?

**Comment by matchai** [comment]
Looks like that did it! 😄
https://github.com/starship/starship/pull/455/checks?check_run_id=243227981

**Comment by svartalf** [comment]
Awesome :) Sorry for a delay with this issue, I have some troubles with my laptop, it ain't that easy to code right now :)

I published new version of this Action, so you can swap back to the `v1` ref:
```yaml
- uses: actions-rs/clippy-check@v1
```
