### ISSUE TITLE
`toolchain` argument doesn't work?

### ISSUE THREAD

**Issue by idubrov** [actions-rs/clippy-check#31]
Seems like `toolchain` argument doesn't really work with `clippy-check`:
```
  /usr/share/rust/.cargo/bin/cargo clippy --message-format=json +nightly --all-features
  error: Found argument '+nightly' which wasn't expected, or isn't valid in this context
  
  USAGE:
      cargo check --message-format <FMT>...
```

I think, `+nightly` should go in front of the `check`.

**Comment by svartalf** [comment]
Yeah, you are right, it is inserted at the wrong position, thanks for a bug report!

https://github.com/actions-rs/clippy-check/blob/1232ac4d6d99b22302832da09c6b742f6b7db31d/src/main.ts#L45-L48

**Comment by warner** [comment]
Thanks for the fix.. looks like the currently published version (1.0.5) doesn't have this fix yet.. wanna make a new release?

**Comment by svartalf** [comment]
Hah, it slipped my mind, sorry about that. Will publish it tomorrow asap!

**Comment by warner** [comment]
awesome, thnaks!
